// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBctu_0-bXKv8vMFV-4gpHH8phfKNAz_Q',
    appId: '1:153823964707:web:afb23d0048da0a5060cb96',
    messagingSenderId: '153823964707',
    projectId: 'metafit-5783f',
    authDomain: 'metafit-5783f.firebaseapp.com',
    storageBucket: 'metafit-5783f.firebasestorage.app',
    measurementId: 'G-NT9RPT70WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCILtMtmnPffhHm-ZNDwhnTiT_fpj09uoo',
    appId: '1:153823964707:android:00e501a48bfcd45760cb96',
    messagingSenderId: '153823964707',
    projectId: 'metafit-5783f',
    storageBucket: 'metafit-5783f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6G3RcDd4UCtSorvPKbZ2nZ-laAfaL-j8',
    appId: '1:153823964707:ios:940e71adc0a67e4e60cb96',
    messagingSenderId: '153823964707',
    projectId: 'metafit-5783f',
    storageBucket: 'metafit-5783f.firebasestorage.app',
    iosBundleId: 'com.example.metafit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6G3RcDd4UCtSorvPKbZ2nZ-laAfaL-j8',
    appId: '1:153823964707:ios:940e71adc0a67e4e60cb96',
    messagingSenderId: '153823964707',
    projectId: 'metafit-5783f',
    storageBucket: 'metafit-5783f.firebasestorage.app',
    iosBundleId: 'com.example.metafit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBctu_0-bXKv8vMFV-4gpHH8phfKNAz_Q',
    appId: '1:153823964707:web:cde089d9bbbfc88160cb96',
    messagingSenderId: '153823964707',
    projectId: 'metafit-5783f',
    authDomain: 'metafit-5783f.firebaseapp.com',
    storageBucket: 'metafit-5783f.firebasestorage.app',
    measurementId: 'G-P5DXG0HT89',
  );
}
